<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/*
| -------------------------------------------------------------------
| Ion Auth
| -------------------------------------------------------------------
|
|
*/

$config['tables']['users'] = 'users';

$config['tables']['groups']          = 'groups';

$config['tables']['users_groups']    = 'users_groups';

$config['tables']['login_attempts']  = 'login_attempts';

/*
| -------------------------------------------------------------------
| Users Table
| -------------------------------------------------------------------
|
|
*/

$config['user_table'] = 'users';

$config['user_table_pk'] = 'id';

/*
| -------------------------------------------------------------------
| Groups
| -------------------------------------------------------------------
|
|
*/

$config['join']['users']  = 'user_id';

$config['join']['groups'] = 'group_id';

/*
| -------------------------------------------------------------------
| Hash Method (sha1 or bcrypt)
| -------------------------------------------------------------------
|
|
*/

$config['hash_method']    = 'bcrypt';

$config['default_rounds'] = 8;

$config['random_rounds']  = FALSE;

$config['min_rounds']     = 5;

$config['max_rounds']     = 9;

$config['salt_prefix']    = '$2y$';

/*
| -------------------------------------------------------------------
| Authentication Options
| -------------------------------------------------------------------
|
|
*/

$config['site_title']                 = 'example.com';
$config['admin_email']                = 'admin@ithinq.net';
$config['default_group']              = 'members';

$config['admin_group']                = 'admin';

$config['identity']                   = 'email';

$config['min_password_length']        = 8;

$config['max_password_length']        = 20;

$config['email_activation']           = FALSE;

$config['manual_activation']          = FALSE;

$config['remember_users']             = TRUE;

$config['user_expire']                = 86500;

$config['user_extend_on_login']       = FALSE;

$config['track_login_attempts']       = FALSE;

$config['track_login_ip_address']     = TRUE;

$config['maximum_login_attempts']     = 3;

$config['lockout_time']               = 600;

$config['forgot_password_expiration'] = 0;

/*
| -------------------------------------------------------------------
| Cookies Options
| -------------------------------------------------------------------
|
|
*/

$config['remember_cookie_name'] = 'remember_code';

$config['identity_cookie_name'] = 'identity';

/*
| -------------------------------------------------------------------
| Email Options
| -------------------------------------------------------------------
|
|
*/

$config['use_ci_email'] = FALSE;

$config['email_config'] = array('mailtype' => 'html',);

/*
| -------------------------------------------------------------------
| Email Template
| -------------------------------------------------------------------
|
|
*/

$config['email_templates'] = 'auth/email/';

/*
| -------------------------------------------------------------------
| Activate Account Email Template
| -------------------------------------------------------------------
|
|
*/

$config['email_activate'] = 'activate.tpl.php';

/*
| -------------------------------------------------------------------
| Forgot Password Email Template
| -------------------------------------------------------------------
|
|
*/

$config['email_forgot_password'] = 'forgot_password.tpl.php';

/*
| -------------------------------------------------------------------
| Forgot Password Complete Email Template
| -------------------------------------------------------------------
|
|
*/

$config['email_forgot_password_complete'] = 'new_password.tpl.php';

/*
| -------------------------------------------------------------------
|  Salt options
| -------------------------------------------------------------------
|
|
*/

$config['salt_length'] = 22;

$config['store_salt']  = FALSE;

/*
| -------------------------------------------------------------------
| Message Delimiters.
| -------------------------------------------------------------------
|
|
*/

$config['delimiters_source']       = 'config';

$config['message_start_delimiter'] = '<p class="alert alert-success">';

$config['message_end_delimiter']   = '</p>';

$config['error_start_delimiter']   = '<p class="alert alert-danger">';

$config['error_end_delimiter']     = '</p>';



/* End of file language.php */
/* Auto generated by Oinvoices Installer on : 2015.02.28 09:02:36 */
/* Location: ./application/config/ion_auth.php */