<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/*
| -------------------------------------------------------------------
| Oinvoices LANGUAGES
| -------------------------------------------------------------------
| Contains the available languages definitions for the front-end.
| Auto-generated by Oinvoicess Language administration.
| Changes made in this file will be overwritten by languages save in Oinvoices.
|
|
*/

// Default admin language code
$config['default_admin_lang'] = 'en';

// Default language code
// This code depends on the language defined through the Oinvoices admin panel
// and will never change during the request process 
$config['default_lang_code'] = '';

// Used language code
// Dynamically changed by the Router depending on the browser, cookie or asked URL
// By default, Oinvoices set it to the default lang code.
$config['detected_lang_code'] = '';

// Available languages
// Languages set through Oinvoices. Includes offline languages
$config['available_languages'] = array(
	'' => NULL
	);

// Online languages
// Languages set online through Oinvoices.
$config['online_languages'] = array(

	);

// Default Translations Language Code
// Used as reference by the translation tool
$config['default_translation_lang_code'] = '';



/* End of file language.php */
/* Auto generated by Oinvoices Installer on : 2015.01.29 08:55:56 */
/* Location: ./application/config/language.php
*